# Generated by Django 2.2 on 2019-04-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='update',
        ),
    ]
